

pipeline{
  agent any;
  stages{
    stage('Pull-Code'){
          steps{
			echo "Pulling Updated Code To Server.....***** "
			sh 'git stash'
              git branch: 'feature/tejaswini', credentialsId: 'tejaswinis@siddhatech.com', url: 'https://github.com/RaghavendraPrabhu/siddhatechtest.git'
          }
        }
        
    
  }
    

  
}

